hibernate:
    hbm2ddl:
        auto: update
    cache:
        queries: true
    dialect: org.hibernate.dialect.H2Dialect
spring:
    datasource:
        driverClassName: org.h2.Driver
        url:   jdbc:h2:~/h2/gorm
        username: root
        password: ""

grails:
    gorm:
        flushMode: AUTO



